name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag knightsarai/react-doc-tic-tac-toe
      
    - name: test the app
      run: docker run -e CI=true react-doc-tic-tac-toe_tic-tac-toe npm run test
